apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k3hfss80v-python 
  janus-idp.io/tekton: k3hfss80v-python
  backstage.io/kubernetes-id: k3hfss80v-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k3hfss80v-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml